version: "3.7"

services:

  redis:
    image: redis
  
  signer:
    build: ./
    environment:
      REDIS_HOSTNAME: redis
      ROTATION_PERIOD: 300s
      ASYMMETRIC_SIGNING: "true"
    ports:
      - 3000:3000
