version: "3.6"

services:

  redis:
    image: redis
  
  signer:
    build: ./
    environment:
      - REDIS_HOSTNAME=redis
      - ROTATION_PERIOD
      - DISABLE_ROTATING
    ports:
      - ${PORT}:3000